(function(){var ea,pa,qa,fa,i,ra,sa,ga,ta,ua,va,t,T,U,ha,ia,wa,xa,n,ya,V,za,ja,Aa,Ba,Ca,Da,W,ka,la,Ea,w,J,X,k,x,K,L,ma,Fa,B,o,Ga,Ha,M,Y,p,Ia,y,Z,N,q,C,O,na,G,oa,j,u=function(c,a){return function(){return c.apply(a,arguments)}},La=Array.prototype.indexOf||function(c){for(var a=0,b=this.length;a<b;a++)if(this[a]===c)return a;return-1},Ma=Object.prototype.hasOwnProperty,H=function(c,a){function b(){this.constructor=c}for(var d in a)if(Ma.call(a,d))c[d]=a[d];b.prototype=a.prototype;c.prototype=new b;
c.__super__=a.prototype;return c};C=Math.round;B=Math.floor;y=Math.random;G=Math.sqrt;p=Math.min;Y=Math.max;K=Math.abs;if(window.console==null)window.console={log:function(){}};k=640;ka=false;T=250;V=500;za=-k*0;ta=-k*1;va=-k*2;ra=-k*3;if(navigator.userAgent.match(/i(Pad|Phone|Pod)/i)){ha=ka=true;V=350;T=150}else ha=false;ea=true;la=false;Da={background:"gfx/background.jpg",brick_orange:"gfx/brick_orange.png",brick_green:"gfx/brick_green.png",brick_blue:"gfx/brick_blue.png",brick_immortal:"gfx/brick_immortal.png",
brick_tnt:"gfx/brick_tnt.png",brick_nuke:"gfx/brick_nuke.png",brick_hard0:"gfx/brick_hard0.png",brick_hard1:"gfx/brick_hard1.png",brick_hard2:"gfx/brick_hard2.png",brick_xtraball:"gfx/brick_xtraball.png",brick_explosion:"gfx/explosion.png",ball:"gfx/ball.png",paddle:"gfx/paddle.png",paddle_light:"gfx/paddle_light.png",pong:"sfx/pong.ogg",ping:"sfx/ping.ogg",thud:"sfx/thud.ogg",explosion:"sfx/explosion.ogg",nuke:"sfx/nuke.ogg",multiball:"sfx/multiball.ogg",soundscape:"sfx/soundscape.ogg"};U=false;
o=w=null;n=[];n.push(function(c){var a,b,d,e;b=[j(150,100),j(150,130),j(150,160),j(150,190),j(150,220),j(150,250),j(230,160),j(310,100),j(310,130),j(310,160),j(310,190),j(310,220),j(310,250),j(450,160),j(450,190),j(450,220),j(450,250)];d=0;for(e=b.length;d<e;d++){a=b[d];c.bricks.push(new i(j(a.x,a.y+50)))}return c.bricks.push(new J(j(450,100)))});n.push(function(c){var a,b,d,e,f,g;g=[];for(d=0;d<5;d++)g.push(function(){var h;h=[];for(a=0;a<7;a++){e=a*i.width+i.width;f=d*(i.height+2)+i.height+80;b=
["orange","green"][d&1^a&1];h.push(c.bricks.push(new ga(j(e,f),b)))}return h}());return g});n.push(function(c){var a,b,d,e,f,g;g=[];for(d=0;d<5;d++)g.push(function(){var h;h=[];for(a=0;a<7;a++){e=a*i.width+i.width;f=d*(i.height+2)+i.height+80;b=["orange","blue"][d&1^a&1];h.push(d===1&&a%3===0?c.bricks.push(new J(j(e,f))):c.bricks.push(new ga(j(e,f),b)))}return h}());return g});M=function(c){return function(a){var b,d,e,f,g,h,m;d=B(k/i.width)-1;f=B(380*c/(i.height+10));m=[];for(e=0;0<=f?e<f:e>f;0<=
f?e+=1:e-=1)m.push(function(){var l;l=[];for(b=0;0<=d?b<d:b>d;0<=d?b+=1:b-=1){g=b*i.width+i.width;h=e*(i.height+2)+i.height+80;l.push(function(){switch(e%3){case 0:return e===0&&b===~~(d/2)?a.bricks.push(new x(j(g,h))):a.bricks.push(new t(j(g,h)));case 1:return a.bricks.push(new i(j(g,h)));case 2:return b%3===0?a.bricks.push(new J(j(g,h))):a.bricks.push(new t(j(g,h)))}}())}return l}());return m}};n.push(M(0.4));n.push(function(c){var a,b,d,e;for(b=0;b<3;b++)for(a=0;a<7;a++){d=a*i.width+i.width;e=
b*i.height*3+i.height+80;c.bricks.push(new t(j(d,e)))}return c.bricks.push(new x(j(k/2,i.height*5)))});n.push(function(c){var a,b,d,e,f;f=[];for(b=0;b<2;b++)f.push(function(){var g;g=[];for(a=0;a<7;a++)if(!(a&1)){d=a*i.width+i.width;e=b*(i.height+2)+i.height+80;g.push(b===1?c.bricks.push(new ia(j(d,e))):c.bricks.push(new J(j(d,e))))}return g}());return f});n.push(M(0.5));n.push(function(c){var a,b,d,e,f,g;g=[];for(d=0;d<5;d++)g.push(function(){var h;h=[];for(b=0;b<7;b++){e=b*i.width+i.width;f=d*(i.height+
2)+i.height+80;a=d===2&&b===3?ja:t;h.push(c.bricks.push(new a(j(e,f))))}return h}());return g});n.push(M(0.7));n.push(function(c){var a,b,d,e,f;f=[];for(b=0;b<5;b++)f.push(function(){var g;g=[];for(a=0;a<7;a++){d=a*i.width+i.width;e=b*(i.height+2)+i.height+80;g.push(b===0?c.bricks.push(new x(j(d,e))):c.bricks.push(new t(j(d,e))))}return g}());return f});n.push(M(0.8));n.push(function(c){var a,b,d,e,f,g;g=[];for(d=0;d<9;d++)g.push(function(){var h;h=[];for(b=0;b<7;b++){e=b*i.width+i.width;f=d*(i.height+
2)+i.height+80;a=t;if(b%2===1)if(d===0)a=x;else continue;h.push(c.bricks.push(new a(j(e,f))))}return h}());return g});n.push(function(c){var a,b,d,e,f,g;g=[];for(d=0;d<7;d++)g.push(function(){var h;h=[];for(b=0;b<7;b++){e=b*i.width+i.width;f=d*(i.height+2)+i.height+80;a=t;if(d%2===1)a=x;h.push(c.bricks.push(new a(j(e,f))))}return h}());return g});n.push(function(c){var a,b,d,e,f;for(d=0;d<6;d++)for(b=0;b<7;b++){e=b*i.width+i.width;f=d*(i.height+2)+i.height+80;if(d===4&&b===3)a=ja;else if(d===5||b===
0||b===6)a=ia;else if(d===4||d===3||d===2)a=i;else{if(d===0)continue;a=t}c.bricks.push(new a(j(e,f)))}c.bricks.push(new x(j(k-10,30)));return c.bricks.push(new x(j(10,30)))});q={};xa=function(){function c(a){if(a==null)a="perfhub";this.canvas=document.getElementById(a);this.ctx=this.canvas.getContext("2d");this.buckets={};this.buckets.keys=[];this.buckets.values=[];this.sample=0;this.t=new Date;this.scale=Infinity;this.bucketSize=this.canvas.width/this.sampleWidth;this.ctx.font="12px geo";this.fontHeight=
16;this.visible=false;this.canvas.onclick=u(function(){return this.visible=!this.visible},this)}c.prototype.colors=["red","orange","yellow","green","blue"];c.prototype.sampleWidth=2;c.prototype.start=function(){this.sample=(this.sample+1)%this.bucketSize;return this.t=new Date};c.prototype.tick=function(a){var b,d;b=this.buckets[a];if(!b){b=this.buckets[a]={average:0,samples:function(){var e,f,g;g=[];e=0;for(f=this.bucketSize;0<=f?e<=f:e>=f;0<=f?e+=1:e-=1)g.push(0);return g}.call(this)};this.buckets.keys.push(a);
this.buckets.values.push(b)}a=new Date;d=a-this.t;this.t=a;b.average-=b.samples[this.sample]/this.bucketSize;b.samples[this.sample]=d;return b.average+=d/this.bucketSize};c.prototype.draw=function(){var a,b,d,e,f,g,h,m,l,z,s;if(this.visible){g=0;d=8+this.fontHeight*(this.buckets.keys.length+2);a=this.canvas.height-d;f=this.buckets.values;h=0;for(m=f.length;h<m;h++){b=f[h];g+=b.average}if(a/g<this.scale){this.scale=a/g/2;this.ctx.fillStyle="black";this.ctx.fillRect(0,0,this.canvas.width,this.canvas.height)}h=
this.canvas.width-this.sampleWidth;m=this.canvas.height;a=g=0;this.ctx.fillStyle="#111";this.ctx.fillRect(0,0,this.canvas.width,d);this.ctx.drawImage(this.canvas,-1,0);s=this.buckets.keys;l=0;for(z=s.length;l<z;l++){f=s[l];d=this.colors[a++%this.colors.length];b=this.buckets[f];e=b.samples[this.sample];e*=this.scale;m-=e;this.ctx.fillStyle=d;this.ctx.fillRect(h,m,this.sampleWidth,e);this.ctx.fillText(""+f+": "+C(b.average*100)/100+" ms",4,4+this.fontHeight*a);g+=b.average}this.ctx.fillStyle="white";
this.ctx.fillText("total: "+C(g*100)/100+" ms / "+C(1E3/g)+" fps",4,4+this.fontHeight*(this.buckets.keys.length+1));this.ctx.fillStyle="black";this.ctx.fillRect(h,0,this.sampleWidth,m)}};return c}();wa=function(){function c(a){this.element=a;this.target=k/2;window.addEventListener("mousemove",u(function(b){return this.onmove(b)},this),false);a=u(function(b){this.onmove(b.touches[0]);return b.preventDefault()},this);this.element.addEventListener("touchstart",a,false);this.element.addEventListener("touchmove",
a,false);this.left=this.element.parentNode.parentNode.offsetLeft}c.prototype.onmove=function(a){return this.target=a.clientX-this.left};return c}();X=function(){function c(a,b){this.x=a;this.y=b}c.prototype.iadd=function(a){this.x+=a.x;this.y+=a.y;return this};c.prototype.set=function(a,b){this.x=a;this.y=b;return this};c.prototype.add=function(a){return new c(this.x+a.x,this.y+a.y)};c.prototype.sub=function(a){return new c(this.x-a.x,this.y-a.y)};c.prototype.mul=function(a){return new c(this.x*a.x,
this.y*a.y)};c.prototype.muls=function(a){return new c(this.x*a,this.y*a)};c.prototype.imuls=function(a){this.x*=a;this.y*=a;return this};c.prototype.divs=function(a){return this.muls(1/a)};c.prototype.mag=function(){return G(this.x*this.x+this.y*this.y)};c.prototype.normalize=function(){return this.divs(this.mag())};c.prototype.copy=function(){return new c(this.x,this.y)};c.prototype.valueOf=function(){throw"Tried to use V2 as scalar";};c.prototype.toString=function(){return"v2("+this.x+", "+this.y+
")"};return c}();X.random=function(){return(new X(y()-0.5,y()-0.5)).normalize()};j=function(c,a){return new X(c,a)};qa=function(){function c(){var a,b,d;this.maxChannels=15;this.channels=[];b=0;for(d=this.maxChannels;0<=d?b<d:b>d;0<=d?b+=1:b-=1){a=document.createElement("audio");a.used=new Date*1;this.channels.push(a)}}c.prototype.play=function(a,b,d){var e,f,g,h;if(b==null)b=1;if(!ea)return false;e=q[a].src;h=this.channels;f=0;for(g=h.length;f<g;f++){a=h[f];if(a.src===e&&this.playElement(a,e,b,d))return true}this.channels.sort(function(m,
l){return m.used>l.used});h=this.channels;f=0;for(g=h.length;f<g;f++){a=h[f];if(this.playElement(a,e,b,d))return true}return false};c.prototype.playElement=function(a,b,d,e){if(a.paused||a.ended)if(a.currentTime===0){if(a.src!==b)a.src=b;a.volume=d;a.used=new Date*1;a.play();if(e)if(La.call(a,"loop")>=0)a.loop=true;else a.addEventListener("ended",function(){return a.play()},false);return true}else{a.currentTime=0;a.pause()}return false};return c}();L=null;W=function(){function c(a,b,d){this.center=
a;this.width=b;this.height=d;this.left=this.center.x-this.width*0.5;this.right=this.center.x+this.width*0.5;this.top=this.center.y-this.height*0.5;this.bottom=this.center.y+this.height*0.5}c.prototype.recalc=function(){this.left=this.center.x-this.width*0.5;this.right=this.center.x+this.width*0.5;this.top=this.center.y-this.height*0.5;return this.bottom=this.center.y+this.height*0.5};return c}();Z=function(c,a,b){var d,e;c=new W(c.center,c.width+a.radius*2,c.height+a.radius*2);if(!(b.x<c.left||b.x>
c.right||b.y>c.bottom||b.y<c.top))return c.left<(d=a.center.x)&&d<c.right?"y":c.top<(e=a.center.y)&&e<a.center.top?"x":"xy"};sa=function(){return function(c,a){this.center=c;this.radius=a}}();fa=function(){function c(a,b){this.position=a;this.velocity=b;this.shape=new sa(this.position,10)}c.prototype.draw=function(a){var b;b=q.ball;a.globalAlpha=0.25;a.drawImage(b,this.shape.center.x-b.width*0.5,this.shape.center.y-b.height*0.5);a.globalAlpha=1;a.globalCompositeOperation="lighter";a.drawImage(b,this.shape.center.x-
b.width*0.5,this.shape.center.y-b.height*0.5);return a.globalCompositeOperation="source-over"};return c}();Ea=function(){function c(){this.total=0;this.multiplier=1;this.hits=this.pending=0}c.prototype.add=function(a){this.pending+=a;this.hits+=1;return this.multiplier=B(G(this.hits))};c.prototype.earn=function(){this.total+=this.pending*this.multiplier;return this.reset()};c.prototype.reset=function(){this.multiplier=1;return this.pending=this.hits=0};return c}();i=function(){function c(a){this.position=
a;this.shape=new W(this.position,c.width,c.height);this.destroyed=false}c.prototype.image="brick_orange";c.prototype.sound="pong";c.prototype.score=100;c.prototype.draw=function(a){return a.drawImage(q[this.image],this.shape.left,this.shape.top)};c.prototype.hit=function(a){this.destroyed=true;return a.score.add(this.score)};return c}();i.width=80;i.height=30;ia=function(){function c(){c.__super__.constructor.apply(this,arguments)}H(c,i);c.prototype.image="brick_immortal";c.prototype.sound="thud";
c.prototype.hit=function(a,b){if(b)return c.__super__.hit.call(this,a)};return c}();ga=function(){function c(a,b){c.__super__.constructor.call(this,a);this.image="brick_"+b}H(c,i);return c}();t=function(){function c(){c.__super__.constructor.apply(this,arguments)}H(c,i);c.prototype.image="brick_hard0";c.prototype.hits=0;c.prototype.score=200;c.prototype.sound="ping";c.prototype.hit=function(a){this.hits++;if(this.hits>2)return c.__super__.hit.call(this,a);else{this.image="brick_hard"+this.hits;return a.score.add(100)}};
return c}();J=function(){function c(){c.__super__.constructor.apply(this,arguments)}H(c,i);c.prototype.image="brick_tnt";c.prototype.blastRadius=i.width;c.prototype.sound="explosion";c.prototype.score=200;c.prototype.hit=function(a){var b,d,e,f,g;c.__super__.hit.call(this,a);a.sprites.push(new pa(q.brick_explosion,128,this.shape.center));f=a.bricks;g=[];d=0;for(e=f.length;d<e;d++){b=f[d];g.push(!b.destroyed&&b.shape.center.sub(this.shape.center).mag()<=this.blastRadius?b.hit(a,true):void 0)}return g};
return c}();ja=function(){function c(){c.__super__.constructor.apply(this,arguments)}H(c,i);c.prototype.image="brick_nuke";c.prototype.sound="nuke";c.prototype.score=1E3;c.prototype.hit=function(a){var b,d,e,f,g;Ia(o,this.shape.center);c.__super__.hit.call(this,a);f=a.bricks;g=[];d=0;for(e=f.length;d<e;d++){b=f[d];g.push(function(){var h;for(h=[];!b.destroyed;)h.push(b.hit(a,true));return h}())}return g};return c}();x=function(){function c(){c.__super__.constructor.apply(this,arguments)}H(c,i);c.prototype.image=
"brick_xtraball";c.prototype.hit=function(a){c.__super__.hit.call(this,a);L.play("multiball");return a.balls.push(new fa(this.shape.center.copy(),j(0,-T)))};return c}();Aa=function(){function c(a){this.position=a;this.shape=new W(this.position,100,20);this.acceleration=this.velocity=0;this.target=this.position.x}c.prototype.image="paddle";c.prototype.draw=function(a){var b,d,e,f;a.drawImage(q[this.image],this.shape.left-20,this.shape.top-20);e=this.shape.left+10;d=this.shape.width*0.75;f=this.shape.top+
10;b=this.shape.height*0.75;a.globalCompositeOperation="lighter";a.drawImage(q.background,e,f,d,b,this.shape.left,this.shape.top,this.shape.width,this.shape.height);a.drawImage(q.background,e,f,d,b,this.shape.left+2,this.shape.top+2,this.shape.width-2,this.shape.height-2);a.drawImage(q.paddle_light,this.shape.left-20,this.shape.top-20);return a.globalCompositeOperation="source-over"};return c}();Ba=function(){return function(c,a,b){this.position=c;this.velocity=a;this.ttl=b}}();Ca=function(){function c(a){var b;
this.particles=Array(a);this.i=this.t=0;this.gravity=j(0,300);for(b=0;0<=a?b<a:b>a;0<=a?b+=1:b-=1)this.particles[b]=new Ba(j(0,0),j(0,0),0)}c.prototype.spawn=function(a,b,d,e,f){var g,h;for(g=0;0<=f?g<=f:g>=f;0<=f?g+=1:g-=1){h=this.particles[this.i];h.position=a.copy();h.velocity=b.normalize().mul(j(0.5-y(),0.5-y())).normalize().muls(d*y());h.ttl=this.t+e;this.i=(this.i+1)%this.particles.length}};c.prototype.tick=function(a){var b,d,e,f;this.t+=a;f=this.particles;d=0;for(e=f.length;d<e;d++){b=f[d];
if(b.ttl>this.t){b.velocity.iadd(this.gravity.muls(a));b.position.iadd(b.velocity.muls(a))}}};c.prototype.draw=function(a){var b,d,e,f,g;g=this.particles;e=0;for(f=g.length;e<f;e++){d=g[e];if(d.ttl>this.t){b=G(d.ttl-this.t);a.fillStyle="rgba(255, 205, 80, "+b+")";a.fillRect(d.position.x,d.position.y,1,1)}}};return c}();pa=function(){function c(a,b,d){this.img=a;this.width=b;this.center=d;this.frame=0;this.frames=this.img.width/this.width}c.prototype.draw=function(a){a.drawImage(this.img,~~this.frame*
this.width,0,this.width,this.img.height,this.center.x-this.width*0.5,this.center.y-this.img.height*0.5,this.width,this.img.height);return this.frame=(this.frame+0.5)%this.frames};return c}();ua=function(){function c(a){this.canvas=a;this.ctx=this.canvas.getContext("2d");this.input=new wa(this.canvas);this.warmup=10;this.reset()}c.prototype.reset=function(){var a;try{a=localStorage["spacebreak.level"]*1}catch(b){a=0}this.scene={level:a,gameover:false,victory:false,score:new Ea,ballsLeft:3,bricks:[],
sprites:[],balls:[new fa(j(0,0),j(0,0))],paddle:new Aa(j(k/2,430))};this.particles=new Ca(100);this.nextLevel();this.perfhub=new xa;return this.perfhub.start()};c.prototype.nextLevel=function(){this.scene.ballsLeft+=1;this.scene.bricks=[];localStorage["spacebreak.level"]=this.scene.level;if(this.scene.level<n.length)n[this.scene.level++](this.scene);else{localStorage["spacebreak.level"]=0;this.scene.gameover=true;this.scene.victory=true}this.scene.score.earn();this.scene.sprites=[];return this.newBall()};
c.prototype.newBall=function(a){var b,d,e,f,g;if(!a)this.scene.balls=[a=this.scene.balls[0]];if(this.scene.balls.length>1){b=[];g=this.scene.balls;e=0;for(f=g.length;e<f;e++){d=g[e];d!==a&&b.push(d)}this.scene.balls=b}else{this.scene.score.reset();if(this.scene.ballsLeft--){a=this.scene.balls[0];b=Y(p(k-a.shape.radius,this.scene.paddle.shape.center.x),a.shape.radius);a.shape.center.set(b,this.scene.paddle.shape.top-a.shape.radius-1);return a.velocity=j(y()-0.5,y()-2).normalize().muls(T)}else return this.scene.gameover=
true}};c.prototype.tick=function(a){if(this.warmup>0){a<0.05&&this.warmup--;a=1.0E-5}for(this.perfhub.tick("waiting");a>0.05;){this.physics(0.05);a-=0.05}this.physics(a);this.perfhub.tick("physics");this.render();this.perfhub.tick("render");this.perfhub.draw();this.perfhub.tick("perfhub");this.perfhub.start();return!this.scene.gameover};c.prototype.physics=function(a){var b,d,e,f;this.paddlePhysics(a);f=this.scene.balls;d=0;for(e=f.length;d<e;d++){b=f[d];this.ballPhysics(a,b)}this.particles.tick(a);
e=this.scene.bricks;b=0;for(d=e.length;b<d;b++){a=e[b];if(!a.destroyed)return}return this.nextLevel()};c.prototype.ballPhysics=function(a,b){var d,e,f,g,h,m,l,z,s;m="pong";h=b.shape;f=b.position.add(b.velocity.muls(a));if(!(h.radius<=(e=f.x)&&e<=k-h.radius))d="x";if(!(h.radius<=(l=f.y)&&l<=480-h.radius)){if(480-h.radius<=f.y){this.newBall(b);return}d=d==="x"?"xy":"y"}if(!d&&!((d=Z(this.scene.paddle.shape,h,f))&&(g=true))){s=this.scene.bricks;l=0;for(z=s.length;l<z;l++){e=s[l];if(!e.destroyed&&(d=
Z(e.shape,h,f))){e.hit(this.scene);m=e.sound;break}}if(d==="xy")d="x"}if(d==="x")b.velocity.x*=-1;else if(d==="y")b.velocity.y*=-1;else if(d==="xy"){b.velocity.x*=-1;b.velocity.y*=-1}if(g){b.velocity.x+=this.scene.paddle.velocity*10;this.scene.balls.length===1&&this.scene.score.earn()}if(d){d=p(1,b.velocity.mag()/V);L.play(m,d);if(K(b.velocity.y*2)<K(b.velocity.x))b.velocity.x*=0.8;b.velocity=b.velocity.normalize().muls(p(b.velocity.mag()*1.01,V));return this.particles.spawn(f.copy(),b.velocity.muls(0.5),
b.velocity.mag(),1,25)}else return b.position.iadd(b.velocity.muls(a))};c.prototype.paddlePhysics=function(){var a,b,d,e,f;this.scene.paddle.target=this.input.target;this.scene.paddle.acceleration=(this.scene.paddle.target-this.scene.paddle.shape.center.x)*0.2;this.scene.paddle.velocity+=this.scene.paddle.acceleration;this.scene.paddle.velocity*=0.7;this.scene.paddle.shape.center.x+=this.scene.paddle.velocity;this.scene.paddle.shape.center.x=p(k-this.scene.paddle.shape.width*0.5,Y(this.scene.paddle.shape.width*
0.5,this.scene.paddle.shape.center.x));this.scene.paddle.shape.recalc();e=this.scene.balls;b=0;for(d=e.length;b<d;b++){a=e[b];a=a.shape;if(Z(this.scene.paddle.shape,a,a.center)){a.center.x+=this.scene.paddle.velocity;if(!(a.radius<=(f=a.center.x)&&f<=k-a.radius)){a.center.x-=this.scene.paddle.velocity;this.scene.paddle.shape.center.x-=this.scene.paddle.velocity;this.scene.paddle.shape.recalc()}break}}return[]};c.prototype.render=function(){var a,b,d,e,f;this.ctx.drawImage(q.background,0,0);this.particles.draw(this.ctx);
this.scene.paddle.draw(this.ctx);e=this.scene.bricks;b=0;for(d=e.length;b<d;b++){a=e[b];a.destroyed||a.draw(this.ctx)}e=this.scene.balls;b=0;for(d=e.length;b<d;b++){a=e[b];a.draw(this.ctx)}b=[];f=this.scene.sprites;d=0;for(e=f.length;d<e;d++){a=f[d];a.draw(this.ctx);a.frame!==0&&b.push(a)}this.scene.sprites=b;this.ctx.fillStyle="white";this.ctx.textAlign="center";this.ctx.textBaseline="top";if(this.warmup>0){this.ctx.font="40px geo";this.ctx.fillStyle="red";this.ctx.fillText("WARMING UP... PLEASE WAIT",
k/2,-5);this.ctx.fillStyle="white"}else{this.ctx.font="60px geo";this.ctx.fillText(this.scene.score.total,k/2,-5)}this.ctx.font="16px geo";if(this.scene.ballsLeft>1)this.ctx.fillText(""+this.scene.ballsLeft+" balls left",k/2,50);else this.scene.ballsLeft===1?this.ctx.fillText(""+this.scene.ballsLeft+" ball left",k/2,50):this.ctx.fillText("no ball left",k/2,50);b=["white","yellow","orange","red","green","magenta"];if(this.scene.score.pending){this.ctx.font="24px geo";a=p(B((this.scene.score.multiplier-
1)/2),b.length);this.ctx.fillStyle=b[a];a=this.scene.score.multiplier>1?"+ "+this.scene.score.multiplier+" x "+this.scene.score.pending:"+ "+this.scene.score.pending;this.ctx.fillText(a,k/2,70)}};return c}();ya=function(){function c(a){this.resources={};this.failed=this.pending=0;this.audio=true;this.load(a)}c.prototype._success=function(a,b){if(this.resources[a]==null){this.pending--;return this.resources[a]=b}};c.prototype._error=function(a,b){this.failed++;this.pending--;return b.resource=a};c.prototype.load=
function(a){var b,d;for(b in a){d=a[b];if(/\.(jpe?g|gif|png)$/.test(d))this.loadImage(b,d);else if(/\.(og(g|a)|mp3)$/.test(d))this.loadAudio(b,d);else throw"unknow resource type "+d;this.pending++}};c.prototype.loadImage=function(a,b){var d;d=new Image;d.onload=u(function(){return this._success(a,d)},this);d.onerror=u(function(e){return this._error(a,e)},this);return d.src=b};c.prototype.loadAudio=function(a,b){var d,e;d=document.createElement("audio");d.preload="auto";d.autobuffer=true;e=u(function(){console.log("can play");
d.pause();d.volume=1;return this._success(a,{src:d.src})},this);d.addEventListener("canplaythrough",e,false);d.addEventListener("ended",e,false);d.addEventListener("error",u(function(f){return this._error(a,f)},this),false);if((b.slice(-4)===".ogg"||b.slice(-4)===".oga")&&d.canPlayType('audio/ogg; codecs="vorbis"')!=="probably"){this.audio=false;this._error(a,"no support for ogg")}else{d.src=b;e=u(function(){d.play();console.log("playing",d);if(d.paused){this.audio=false;console.log("audio paused after play");
return this._error(a,"audio not play()able")}else return d.volume=0},this);return setTimeout(e,10*this.pending)}};return c}();Ha=function(){var c,a,b,d,e,f;a=document.getElementById("c");a.width=k;a.height=480;d=a.getContext("2d");window.loader=e=new ya(Da);q=e.resources;L=new qa;b=u(function(){if(e.pending>0){d.fillStyle="white";d.clearRect(0,0,k,480);d.textAlign="center";d.textBaseline="top";d.font="50px geo";d.fillText("LOADING",k/2,100);d.font="16px geo";d.fillText(""+e.pending+" resources left",
k/2,140);return setTimeout(b,1E3)}else{ea=e.audio;return oa(a)}},this);if(ha){c=document.createElement("audio");c.src="sfx/soundscape.mp3";c.loop=true;window.setInterval(function(){if(c.currentTime>c.duration-5)return c.currentTime=0},1E3);c.play()}return b()};O=function(c){o&&o.ctx.clearRect(0,0,k,480);w&&w.isRunning()&&w.pause();return document.getElementById("frame").style.left=""+c+"px"};window.newGame=function(){localStorage["spacebreak.level"]=0;return Fa()};window.continueGame=Fa=function(){O(ta);
return o?oa():Ha()};window.menu=function(){O(za);return na()};window.highscores=Ga=function(){var c;O(va);w&&!w.isRunning()&&w.resume();if(o){c=o.scene.score.total;c=o.scene.victory?"I just finished #spacebreak #html5 #game with a score of "+c+". :)":"I scored "+c+" at #spacebreak #html5 #game";return document.getElementById("twattext").value=c}};window.credits=function(){return O(ra)};oa=function(c){var a,b,d;if(o)o.reset();else window.game=o=new ua(c);d=new Date;a=function(){var e,f;e=new Date;
f=e-d;d=e;if(!o.tick(f*0.001)){U&&clearInterval(U);Ga();return false}return true};if(typeof N!="undefined"&&N!==null){b=function(){if(a())return N(b,c)};N(b,c)}else U=setInterval(a,1);if(!la){L.play("soundscape",0.1,true);la=true}return o.render()};na=function(){var c,a;try{a=localStorage["spacebreak.level"]*1}catch(b){a=0}c=document.getElementsByClassName("continue")[0];if(a){c.style.display="block";return c.innerHTML="Continue level "+(a+1)}else return c.style.display="none"};na();ma=function(c,
a){var b;b=document.createElement("canvas");b.width=c;b.height=a;return b};Ia=function(c,a){var b,d,e,f,g,h,m,l,z,s,Ja,P,$,Q,v,A;h=a.x;m=a.y;g=c.ctx;A=k;P=ka?8:4;v=B(A/P);l=B(480/P);e=ma(v,l);f=ma(A,480);b=e.getContext("2d");f.getContext("2d").drawImage(c.canvas,0,0);b.drawImage(c.canvas,0,0,v,l);g.drawImage(e,0,0,A,480);z=A*1920;d=g.getImageData(0,0,A,480);Q=0;s=c.tick;Ja=Math.PI*2/200;$=b.getImageData(0,0,v,l);return c.tick=function(D){var aa,r,R,I,ba,S,Ka,E,ca,F,da;G=Math.sqrt;Ka=Math.sin;C=Math.round;
S=$.data;aa=d.data;K=Math.abs;p=Math.min;Y=Math.max;Q+=D;for(E=0;0<=v?E<=v:E>=v;0<=v?E+=1:E-=1)for(F=0;0<=l?F<=l:F>=l;0<=l?F+=1:F-=1){D=(F*v+E)*4;r=E*P;R=F*P;ca=h-r;da=m-R;I=G(ca*ca+da*da);ba=Ka(I*Ja+Q*-2)*(100/(1+I/100*(I/100))/Q);r=C(r+ba*(ca/I));R=C(R+ba*(da/I));r=(R*A+r)*4;if(r>z||r<1)$[D+3]=0;else{S[D]=p(255,aa[r]*3.5);S[D+1]=p(255,aa[r+1]*1.5);S[D+2]=p(255,aa[r+2]*1);S[D+3]=p(255,15*K(ba))}}b.putImageData($,0,0);g.drawImage(f,0,0);g.drawImage(e,0,0,A,480);if(Q>2.5)c.tick=s;return true}};N=window.requestAnimationFrame||
window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame;applicationCache.encached=applicationCache.onnoupdate=function(){return console.log("cached")};applicationCache.onupdateready=function(){applicationCache.swapCache();window.location.href=window.location.href;return console.log("cache swaped")};window.twatr=function(){return window.twat=w=(new TWTR.Widget({id:"twatr",version:2,type:"search",search:"#spacebreak",interval:6E3,title:"",subject:"",width:540,height:200,theme:{shell:{background:"transparent",
color:"#ffffff"},tweets:{background:"rgba(255, 255, 255, 0.8)",color:"#444444",links:"#1985b5"}},features:{scrollbar:false,loop:true,live:true,hashtags:true,timestamp:true,avatars:true,toptweets:true,behavior:"default"}})).render().start()}}).call(this);
